apiVersion: v1
kind: Service
metadata:
  name: store
  annotations:
    description: Store Service based on WF Swarm
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    deploymentconfig: store
  type: LoadBalancer
